export const products = [
  {
    name: '"Design is Dead" Dad Cap',
    slug: 'dad-cap',
    description: 'A classic dad cap with hand-drawn "Design is Dead" embroidery. One size fits all.',
    price: 3500,
    category: 'apparel' as const,
    featured: true,
    image: 'dad-cap.png',
  },
  {
    name: '"Design is Dead" T-Shirt',
    slug: 't-shirt',
    description: 'Premium cotton tee with bold "Design is Dead" print. Relaxed fit.',
    price: 4500,
    category: 'apparel' as const,
    featured: true,
    image: 't-shirt.png',
  },
  {
    name: '"Design is Dead" Hoodie',
    slug: 'hoodie',
    description: 'Heavyweight hoodie with front "Design is Dead" print. Kangaroo pocket.',
    price: 8500,
    category: 'apparel' as const,
    featured: true,
    image: 'hoodie.png',
  },
  {
    name: '"Design is Dead" Socks',
    slug: 'socks',
    description: 'Ribbed crew socks with subtle "Design is Dead" knit. One size.',
    price: 1500,
    category: 'apparel' as const,
    featured: false,
    image: 'socks.png',
  },
  {
    name: '"Design is Dead" Tote Bag',
    slug: 'tote-bag',
    description: 'Heavy canvas tote with screen-printed "Design is Dead" graphic.',
    price: 2500,
    category: 'accessories' as const,
    featured: true,
    image: 'tote-bag.png',
  },
  {
    name: '"Design is Dead" Enamel Pin',
    slug: 'enamel-pin',
    description: 'Matte black enamel pin with "Design is Dead" engraving. Butterfly clutch.',
    price: 1000,
    category: 'accessories' as const,
    featured: false,
    image: 'pin.png',
  },
  {
    name: '"Design is Dead" Ceramic Mug',
    slug: 'ceramic-mug',
    description: 'Matte black ceramic mug with wrap-around "Design is Dead" print. 12oz.',
    price: 2000,
    category: 'drinkware' as const,
    featured: false,
    image: 'mug.png',
  },
  {
    name: '"Design is Dead" Water Bottle',
    slug: 'water-bottle',
    description: 'Insulated stainless steel bottle with laser-etched "Design is Dead" mark. 17oz.',
    price: 3000,
    category: 'drinkware' as const,
    featured: false,
    image: 'water-bottle.png',
  },
  {
    name: '"Design is Dead" Sticker Sheet',
    slug: 'sticker-sheet',
    description: 'Sheet of die-cut vinyl stickers in assorted "Design is Dead" typographic styles.',
    price: 1200,
    category: 'stationery' as const,
    featured: false,
    image: 'sticker-sheet.png',
  },
  {
    name: '"Design is Dead" Notebook',
    slug: 'notebook',
    description: 'Hardcover dot-grid notebook with debossed "Design is Dead" cover. 192 pages.',
    price: 1800,
    category: 'stationery' as const,
    featured: false,
    image: 'notebook.png',
  },
]

export const storeSettings = {
  storeName: 'Design is Dead',
  heroTitle: 'Design is Dead',
  heroSubtitle: 'A rebellion against the ordinary. No trends, no seasons — just wearable statements that say what everyone is thinking.',
  newsletterHeading: 'Sign up for our newsletter',
  instagramHandle: '@designisdead',
  footerTagline: 'Rebellion against the ordinary.',
}
